### ISSUE TITLE
BUG: nested_getstate removes Dict trait data

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-bdss#283]
If an instance of `BaseModel` has a `Dict` attribute, this data will be ignored when parsing with `__getstate__`. I guess this happens inside the `nested_getstate`. 

Update:
This is a Traits behaviour. See the code below:
```
>>> from traits.api import HasTraits, Str, Int, Dict
>>> class foo(HasTraits):
...     string = Str("string")
...     integer = Int(42)
...     dictionary = Dict({"d": 1})
... 
>>> f = foo()
>>> f.__getstate__()
{'string': 'string', 'integer': 42, 'dictionary': {'d': 1}, '__traits_version__': '5.1.1'}
>>> f.string.__getstate__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute '__getstate__'
>>> f.integer.__getstate__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute '__getstate__'
>>> f.dictionary.__getstate__()
{'name': 'dictionary', 'name_items': 'dictionary_items'}
```
The difference is that the `Dict` is the only type that implements `__getstate__`, and therefore doesn't raise an `AttributeError`.
To fix this, we could add this extra condition to the `nested_get_state`:
```
            if isinstance(state_dict[key], dict):
                continue
```
to the `nested_getstate` function.

**Comment by Corwinpro** [comment]
Closed by #284
